// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: torrent/torrent.proto

package torrent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MagnetUri     string                 `protobuf:"bytes,1,opt,name=magnet_uri,json=magnetUri,proto3" json:"magnet_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTorrentRequest) Reset() {
	*x = AddTorrentRequest{}
	mi := &file_torrent_torrent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTorrentRequest) ProtoMessage() {}

func (x *AddTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTorrentRequest.ProtoReflect.Descriptor instead.
func (*AddTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{0}
}

func (x *AddTorrentRequest) GetMagnetUri() string {
	if x != nil {
		return x.MagnetUri
	}
	return ""
}

type GetTorrentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTorrentsRequest) Reset() {
	*x = GetTorrentsRequest{}
	mi := &file_torrent_torrent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTorrentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTorrentsRequest) ProtoMessage() {}

func (x *GetTorrentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTorrentsRequest.ProtoReflect.Descriptor instead.
func (*GetTorrentsRequest) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{1}
}

func (x *GetTorrentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DeleteTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTorrentRequest) Reset() {
	*x = DeleteTorrentRequest{}
	mi := &file_torrent_torrent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTorrentRequest) ProtoMessage() {}

func (x *DeleteTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTorrentRequest.ProtoReflect.Descriptor instead.
func (*DeleteTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteTorrentRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type PauseTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTorrentRequest) Reset() {
	*x = PauseTorrentRequest{}
	mi := &file_torrent_torrent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTorrentRequest) ProtoMessage() {}

func (x *PauseTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTorrentRequest.ProtoReflect.Descriptor instead.
func (*PauseTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{3}
}

func (x *PauseTorrentRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type ResumeTorrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeTorrentRequest) Reset() {
	*x = ResumeTorrentRequest{}
	mi := &file_torrent_torrent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeTorrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeTorrentRequest) ProtoMessage() {}

func (x *ResumeTorrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeTorrentRequest.ProtoReflect.Descriptor instead.
func (*ResumeTorrentRequest) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{4}
}

func (x *ResumeTorrentRequest) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

type Torrent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InfoHash      string                 `protobuf:"bytes,1,opt,name=info_hash,json=infoHash,proto3" json:"info_hash,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3" json:"total_size,omitempty"`
	Downloaded    int64                  `protobuf:"varint,4,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	Uploaded      int64                  `protobuf:"varint,5,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	DownloadRate  int64                  `protobuf:"varint,6,opt,name=download_rate,json=downloadRate,proto3" json:"download_rate,omitempty"`
	UploadRate    int64                  `protobuf:"varint,7,opt,name=upload_rate,json=uploadRate,proto3" json:"upload_rate,omitempty"`
	Progress      float64                `protobuf:"fixed64,8,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Torrent) Reset() {
	*x = Torrent{}
	mi := &file_torrent_torrent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Torrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torrent) ProtoMessage() {}

func (x *Torrent) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torrent.ProtoReflect.Descriptor instead.
func (*Torrent) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{5}
}

func (x *Torrent) GetInfoHash() string {
	if x != nil {
		return x.InfoHash
	}
	return ""
}

func (x *Torrent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Torrent) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *Torrent) GetDownloaded() int64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *Torrent) GetUploaded() int64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *Torrent) GetDownloadRate() int64 {
	if x != nil {
		return x.DownloadRate
	}
	return 0
}

func (x *Torrent) GetUploadRate() int64 {
	if x != nil {
		return x.UploadRate
	}
	return 0
}

func (x *Torrent) GetProgress() float64 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *Torrent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type TorrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentResponse) Reset() {
	*x = TorrentResponse{}
	mi := &file_torrent_torrent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentResponse) ProtoMessage() {}

func (x *TorrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentResponse.ProtoReflect.Descriptor instead.
func (*TorrentResponse) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{6}
}

func (x *TorrentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TorrentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type TorrentsListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*Torrent             `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorrentsListResponse) Reset() {
	*x = TorrentsListResponse{}
	mi := &file_torrent_torrent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorrentsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorrentsListResponse) ProtoMessage() {}

func (x *TorrentsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_torrent_torrent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorrentsListResponse.ProtoReflect.Descriptor instead.
func (*TorrentsListResponse) Descriptor() ([]byte, []int) {
	return file_torrent_torrent_proto_rawDescGZIP(), []int{7}
}

func (x *TorrentsListResponse) GetTorrents() []*Torrent {
	if x != nil {
		return x.Torrents
	}
	return nil
}

func (x *TorrentsListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_torrent_torrent_proto protoreflect.FileDescriptor

const file_torrent_torrent_proto_rawDesc = "" +
	"\n" +
	"\x15torrent/torrent.proto\x12\atorrent\"2\n" +
	"\x11AddTorrentRequest\x12\x1d\n" +
	"\n" +
	"magnet_uri\x18\x01 \x01(\tR\tmagnetUri\"*\n" +
	"\x12GetTorrentsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"3\n" +
	"\x14DeleteTorrentRequest\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\tR\binfoHash\"2\n" +
	"\x13PauseTorrentRequest\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\tR\binfoHash\"3\n" +
	"\x14ResumeTorrentRequest\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\tR\binfoHash\"\x8f\x02\n" +
	"\aTorrent\x12\x1b\n" +
	"\tinfo_hash\x18\x01 \x01(\tR\binfoHash\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x03R\ttotalSize\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x04 \x01(\x03R\n" +
	"downloaded\x12\x1a\n" +
	"\buploaded\x18\x05 \x01(\x03R\buploaded\x12#\n" +
	"\rdownload_rate\x18\x06 \x01(\x03R\fdownloadRate\x12\x1f\n" +
	"\vupload_rate\x18\a \x01(\x03R\n" +
	"uploadRate\x12\x1a\n" +
	"\bprogress\x18\b \x01(\x01R\bprogress\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"E\n" +
	"\x0fTorrentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"Z\n" +
	"\x14TorrentsListResponse\x12,\n" +
	"\btorrents\x18\x01 \x03(\v2\x10.torrent.TorrentR\btorrents\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total2\xfb\x02\n" +
	"\x0eTorrentService\x12B\n" +
	"\n" +
	"AddTorrent\x12\x1a.torrent.AddTorrentRequest\x1a\x18.torrent.TorrentResponse\x12I\n" +
	"\vGetTorrents\x12\x1b.torrent.GetTorrentsRequest\x1a\x1d.torrent.TorrentsListResponse\x12H\n" +
	"\rDeleteTorrent\x12\x1d.torrent.DeleteTorrentRequest\x1a\x18.torrent.TorrentResponse\x12F\n" +
	"\fPauseTorrent\x12\x1c.torrent.PauseTorrentRequest\x1a\x18.torrent.TorrentResponse\x12H\n" +
	"\rResumeTorrent\x12\x1d.torrent.ResumeTorrentRequest\x1a\x18.torrent.TorrentResponseB6Z4github.com/KFN002/B-2-Torrent/services/proto/torrentb\x06proto3"

var (
	file_torrent_torrent_proto_rawDescOnce sync.Once
	file_torrent_torrent_proto_rawDescData []byte
)

func file_torrent_torrent_proto_rawDescGZIP() []byte {
	file_torrent_torrent_proto_rawDescOnce.Do(func() {
		file_torrent_torrent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_torrent_torrent_proto_rawDesc), len(file_torrent_torrent_proto_rawDesc)))
	})
	return file_torrent_torrent_proto_rawDescData
}

var file_torrent_torrent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_torrent_torrent_proto_goTypes = []any{
	(*AddTorrentRequest)(nil),    // 0: torrent.AddTorrentRequest
	(*GetTorrentsRequest)(nil),   // 1: torrent.GetTorrentsRequest
	(*DeleteTorrentRequest)(nil), // 2: torrent.DeleteTorrentRequest
	(*PauseTorrentRequest)(nil),  // 3: torrent.PauseTorrentRequest
	(*ResumeTorrentRequest)(nil), // 4: torrent.ResumeTorrentRequest
	(*Torrent)(nil),              // 5: torrent.Torrent
	(*TorrentResponse)(nil),      // 6: torrent.TorrentResponse
	(*TorrentsListResponse)(nil), // 7: torrent.TorrentsListResponse
}
var file_torrent_torrent_proto_depIdxs = []int32{
	5, // 0: torrent.TorrentsListResponse.torrents:type_name -> torrent.Torrent
	0, // 1: torrent.TorrentService.AddTorrent:input_type -> torrent.AddTorrentRequest
	1, // 2: torrent.TorrentService.GetTorrents:input_type -> torrent.GetTorrentsRequest
	2, // 3: torrent.TorrentService.DeleteTorrent:input_type -> torrent.DeleteTorrentRequest
	3, // 4: torrent.TorrentService.PauseTorrent:input_type -> torrent.PauseTorrentRequest
	4, // 5: torrent.TorrentService.ResumeTorrent:input_type -> torrent.ResumeTorrentRequest
	6, // 6: torrent.TorrentService.AddTorrent:output_type -> torrent.TorrentResponse
	7, // 7: torrent.TorrentService.GetTorrents:output_type -> torrent.TorrentsListResponse
	6, // 8: torrent.TorrentService.DeleteTorrent:output_type -> torrent.TorrentResponse
	6, // 9: torrent.TorrentService.PauseTorrent:output_type -> torrent.TorrentResponse
	6, // 10: torrent.TorrentService.ResumeTorrent:output_type -> torrent.TorrentResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_torrent_torrent_proto_init() }
func file_torrent_torrent_proto_init() {
	if File_torrent_torrent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_torrent_torrent_proto_rawDesc), len(file_torrent_torrent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_torrent_torrent_proto_goTypes,
		DependencyIndexes: file_torrent_torrent_proto_depIdxs,
		MessageInfos:      file_torrent_torrent_proto_msgTypes,
	}.Build()
	File_torrent_torrent_proto = out.File
	file_torrent_torrent_proto_goTypes = nil
	file_torrent_torrent_proto_depIdxs = nil
}
