// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: torrent/torrent.proto

package torrent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TorrentService_AddTorrent_FullMethodName    = "/torrent.TorrentService/AddTorrent"
	TorrentService_GetTorrents_FullMethodName   = "/torrent.TorrentService/GetTorrents"
	TorrentService_DeleteTorrent_FullMethodName = "/torrent.TorrentService/DeleteTorrent"
	TorrentService_PauseTorrent_FullMethodName  = "/torrent.TorrentService/PauseTorrent"
	TorrentService_ResumeTorrent_FullMethodName = "/torrent.TorrentService/ResumeTorrent"
)

// TorrentServiceClient is the client API for TorrentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TorrentServiceClient interface {
	AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error)
	GetTorrents(ctx context.Context, in *GetTorrentsRequest, opts ...grpc.CallOption) (*TorrentsListResponse, error)
	DeleteTorrent(ctx context.Context, in *DeleteTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error)
	PauseTorrent(ctx context.Context, in *PauseTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error)
	ResumeTorrent(ctx context.Context, in *ResumeTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error)
}

type torrentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTorrentServiceClient(cc grpc.ClientConnInterface) TorrentServiceClient {
	return &torrentServiceClient{cc}
}

func (c *torrentServiceClient) AddTorrent(ctx context.Context, in *AddTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_AddTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) GetTorrents(ctx context.Context, in *GetTorrentsRequest, opts ...grpc.CallOption) (*TorrentsListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentsListResponse)
	err := c.cc.Invoke(ctx, TorrentService_GetTorrents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) DeleteTorrent(ctx context.Context, in *DeleteTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_DeleteTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) PauseTorrent(ctx context.Context, in *PauseTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_PauseTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *torrentServiceClient) ResumeTorrent(ctx context.Context, in *ResumeTorrentRequest, opts ...grpc.CallOption) (*TorrentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TorrentResponse)
	err := c.cc.Invoke(ctx, TorrentService_ResumeTorrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TorrentServiceServer is the server API for TorrentService service.
// All implementations must embed UnimplementedTorrentServiceServer
// for forward compatibility.
type TorrentServiceServer interface {
	AddTorrent(context.Context, *AddTorrentRequest) (*TorrentResponse, error)
	GetTorrents(context.Context, *GetTorrentsRequest) (*TorrentsListResponse, error)
	DeleteTorrent(context.Context, *DeleteTorrentRequest) (*TorrentResponse, error)
	PauseTorrent(context.Context, *PauseTorrentRequest) (*TorrentResponse, error)
	ResumeTorrent(context.Context, *ResumeTorrentRequest) (*TorrentResponse, error)
	mustEmbedUnimplementedTorrentServiceServer()
}

// UnimplementedTorrentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTorrentServiceServer struct{}

func (UnimplementedTorrentServiceServer) AddTorrent(context.Context, *AddTorrentRequest) (*TorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) GetTorrents(context.Context, *GetTorrentsRequest) (*TorrentsListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTorrents not implemented")
}
func (UnimplementedTorrentServiceServer) DeleteTorrent(context.Context, *DeleteTorrentRequest) (*TorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) PauseTorrent(context.Context, *PauseTorrentRequest) (*TorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PauseTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) ResumeTorrent(context.Context, *ResumeTorrentRequest) (*TorrentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeTorrent not implemented")
}
func (UnimplementedTorrentServiceServer) mustEmbedUnimplementedTorrentServiceServer() {}
func (UnimplementedTorrentServiceServer) testEmbeddedByValue()                        {}

// UnsafeTorrentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TorrentServiceServer will
// result in compilation errors.
type UnsafeTorrentServiceServer interface {
	mustEmbedUnimplementedTorrentServiceServer()
}

func RegisterTorrentServiceServer(s grpc.ServiceRegistrar, srv TorrentServiceServer) {
	// If the following call panics, it indicates UnimplementedTorrentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TorrentService_ServiceDesc, srv)
}

func _TorrentService_AddTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).AddTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_AddTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).AddTorrent(ctx, req.(*AddTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_GetTorrents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTorrentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).GetTorrents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_GetTorrents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).GetTorrents(ctx, req.(*GetTorrentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_DeleteTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).DeleteTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_DeleteTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).DeleteTorrent(ctx, req.(*DeleteTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_PauseTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).PauseTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_PauseTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).PauseTorrent(ctx, req.(*PauseTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TorrentService_ResumeTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTorrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TorrentServiceServer).ResumeTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TorrentService_ResumeTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TorrentServiceServer).ResumeTorrent(ctx, req.(*ResumeTorrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TorrentService_ServiceDesc is the grpc.ServiceDesc for TorrentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TorrentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "torrent.TorrentService",
	HandlerType: (*TorrentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTorrent",
			Handler:    _TorrentService_AddTorrent_Handler,
		},
		{
			MethodName: "GetTorrents",
			Handler:    _TorrentService_GetTorrents_Handler,
		},
		{
			MethodName: "DeleteTorrent",
			Handler:    _TorrentService_DeleteTorrent_Handler,
		},
		{
			MethodName: "PauseTorrent",
			Handler:    _TorrentService_PauseTorrent_Handler,
		},
		{
			MethodName: "ResumeTorrent",
			Handler:    _TorrentService_ResumeTorrent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "torrent/torrent.proto",
}
