// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: security/security.proto

package security

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecurityService_GetSecurityStatus_FullMethodName      = "/security.SecurityService/GetSecurityStatus"
	SecurityService_CheckLeaks_FullMethodName             = "/security.SecurityService/CheckLeaks"
	SecurityService_UpdateSecuritySettings_FullMethodName = "/security.SecurityService/UpdateSecuritySettings"
)

// SecurityServiceClient is the client API for SecurityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecurityServiceClient interface {
	GetSecurityStatus(ctx context.Context, in *SecurityStatusRequest, opts ...grpc.CallOption) (*SecurityStatusResponse, error)
	CheckLeaks(ctx context.Context, in *LeakCheckRequest, opts ...grpc.CallOption) (*LeakCheckResponse, error)
	UpdateSecuritySettings(ctx context.Context, in *UpdateSecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error)
}

type securityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSecurityServiceClient(cc grpc.ClientConnInterface) SecurityServiceClient {
	return &securityServiceClient{cc}
}

func (c *securityServiceClient) GetSecurityStatus(ctx context.Context, in *SecurityStatusRequest, opts ...grpc.CallOption) (*SecurityStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityStatusResponse)
	err := c.cc.Invoke(ctx, SecurityService_GetSecurityStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) CheckLeaks(ctx context.Context, in *LeakCheckRequest, opts ...grpc.CallOption) (*LeakCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeakCheckResponse)
	err := c.cc.Invoke(ctx, SecurityService_CheckLeaks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *securityServiceClient) UpdateSecuritySettings(ctx context.Context, in *UpdateSecurityRequest, opts ...grpc.CallOption) (*SecurityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SecurityResponse)
	err := c.cc.Invoke(ctx, SecurityService_UpdateSecuritySettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecurityServiceServer is the server API for SecurityService service.
// All implementations must embed UnimplementedSecurityServiceServer
// for forward compatibility.
type SecurityServiceServer interface {
	GetSecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error)
	CheckLeaks(context.Context, *LeakCheckRequest) (*LeakCheckResponse, error)
	UpdateSecuritySettings(context.Context, *UpdateSecurityRequest) (*SecurityResponse, error)
	mustEmbedUnimplementedSecurityServiceServer()
}

// UnimplementedSecurityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecurityServiceServer struct{}

func (UnimplementedSecurityServiceServer) GetSecurityStatus(context.Context, *SecurityStatusRequest) (*SecurityStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSecurityStatus not implemented")
}
func (UnimplementedSecurityServiceServer) CheckLeaks(context.Context, *LeakCheckRequest) (*LeakCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckLeaks not implemented")
}
func (UnimplementedSecurityServiceServer) UpdateSecuritySettings(context.Context, *UpdateSecurityRequest) (*SecurityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSecuritySettings not implemented")
}
func (UnimplementedSecurityServiceServer) mustEmbedUnimplementedSecurityServiceServer() {}
func (UnimplementedSecurityServiceServer) testEmbeddedByValue()                         {}

// UnsafeSecurityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecurityServiceServer will
// result in compilation errors.
type UnsafeSecurityServiceServer interface {
	mustEmbedUnimplementedSecurityServiceServer()
}

func RegisterSecurityServiceServer(s grpc.ServiceRegistrar, srv SecurityServiceServer) {
	// If the following call panics, it indicates UnimplementedSecurityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecurityService_ServiceDesc, srv)
}

func _SecurityService_GetSecurityStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SecurityStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).GetSecurityStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_GetSecurityStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).GetSecurityStatus(ctx, req.(*SecurityStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_CheckLeaks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeakCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).CheckLeaks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_CheckLeaks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).CheckLeaks(ctx, req.(*LeakCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecurityService_UpdateSecuritySettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSecurityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecurityServiceServer).UpdateSecuritySettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecurityService_UpdateSecuritySettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecurityServiceServer).UpdateSecuritySettings(ctx, req.(*UpdateSecurityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SecurityService_ServiceDesc is the grpc.ServiceDesc for SecurityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecurityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "security.SecurityService",
	HandlerType: (*SecurityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSecurityStatus",
			Handler:    _SecurityService_GetSecurityStatus_Handler,
		},
		{
			MethodName: "CheckLeaks",
			Handler:    _SecurityService_CheckLeaks_Handler,
		},
		{
			MethodName: "UpdateSecuritySettings",
			Handler:    _SecurityService_UpdateSecuritySettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "security/security.proto",
}
