// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: security/security.proto

package security

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SecurityStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityStatusRequest) Reset() {
	*x = SecurityStatusRequest{}
	mi := &file_security_security_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStatusRequest) ProtoMessage() {}

func (x *SecurityStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStatusRequest.ProtoReflect.Descriptor instead.
func (*SecurityStatusRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{0}
}

type SecurityStatusResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	KillSwitchActive     bool                   `protobuf:"varint,1,opt,name=kill_switch_active,json=killSwitchActive,proto3" json:"kill_switch_active,omitempty"`
	DnsProtectionActive  bool                   `protobuf:"varint,2,opt,name=dns_protection_active,json=dnsProtectionActive,proto3" json:"dns_protection_active,omitempty"`
	IpObfuscationActive  bool                   `protobuf:"varint,3,opt,name=ip_obfuscation_active,json=ipObfuscationActive,proto3" json:"ip_obfuscation_active,omitempty"`
	DataEncryptionActive bool                   `protobuf:"varint,4,opt,name=data_encryption_active,json=dataEncryptionActive,proto3" json:"data_encryption_active,omitempty"`
	OverallSecurityScore int32                  `protobuf:"varint,5,opt,name=overall_security_score,json=overallSecurityScore,proto3" json:"overall_security_score,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SecurityStatusResponse) Reset() {
	*x = SecurityStatusResponse{}
	mi := &file_security_security_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityStatusResponse) ProtoMessage() {}

func (x *SecurityStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityStatusResponse.ProtoReflect.Descriptor instead.
func (*SecurityStatusResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{1}
}

func (x *SecurityStatusResponse) GetKillSwitchActive() bool {
	if x != nil {
		return x.KillSwitchActive
	}
	return false
}

func (x *SecurityStatusResponse) GetDnsProtectionActive() bool {
	if x != nil {
		return x.DnsProtectionActive
	}
	return false
}

func (x *SecurityStatusResponse) GetIpObfuscationActive() bool {
	if x != nil {
		return x.IpObfuscationActive
	}
	return false
}

func (x *SecurityStatusResponse) GetDataEncryptionActive() bool {
	if x != nil {
		return x.DataEncryptionActive
	}
	return false
}

func (x *SecurityStatusResponse) GetOverallSecurityScore() int32 {
	if x != nil {
		return x.OverallSecurityScore
	}
	return 0
}

type LeakCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeakCheckRequest) Reset() {
	*x = LeakCheckRequest{}
	mi := &file_security_security_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeakCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeakCheckRequest) ProtoMessage() {}

func (x *LeakCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeakCheckRequest.ProtoReflect.Descriptor instead.
func (*LeakCheckRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{2}
}

type LeakCheckResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	IpLeakDetected  bool                   `protobuf:"varint,1,opt,name=ip_leak_detected,json=ipLeakDetected,proto3" json:"ip_leak_detected,omitempty"`
	DnsLeakDetected bool                   `protobuf:"varint,2,opt,name=dns_leak_detected,json=dnsLeakDetected,proto3" json:"dns_leak_detected,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LeakCheckResponse) Reset() {
	*x = LeakCheckResponse{}
	mi := &file_security_security_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeakCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeakCheckResponse) ProtoMessage() {}

func (x *LeakCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeakCheckResponse.ProtoReflect.Descriptor instead.
func (*LeakCheckResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{3}
}

func (x *LeakCheckResponse) GetIpLeakDetected() bool {
	if x != nil {
		return x.IpLeakDetected
	}
	return false
}

func (x *LeakCheckResponse) GetDnsLeakDetected() bool {
	if x != nil {
		return x.DnsLeakDetected
	}
	return false
}

func (x *LeakCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateSecurityRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	KillSwitchEnabled     bool                   `protobuf:"varint,1,opt,name=kill_switch_enabled,json=killSwitchEnabled,proto3" json:"kill_switch_enabled,omitempty"`
	DnsProtectionEnabled  bool                   `protobuf:"varint,2,opt,name=dns_protection_enabled,json=dnsProtectionEnabled,proto3" json:"dns_protection_enabled,omitempty"`
	IpObfuscationEnabled  bool                   `protobuf:"varint,3,opt,name=ip_obfuscation_enabled,json=ipObfuscationEnabled,proto3" json:"ip_obfuscation_enabled,omitempty"`
	DataEncryptionEnabled bool                   `protobuf:"varint,4,opt,name=data_encryption_enabled,json=dataEncryptionEnabled,proto3" json:"data_encryption_enabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UpdateSecurityRequest) Reset() {
	*x = UpdateSecurityRequest{}
	mi := &file_security_security_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSecurityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSecurityRequest) ProtoMessage() {}

func (x *UpdateSecurityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSecurityRequest.ProtoReflect.Descriptor instead.
func (*UpdateSecurityRequest) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSecurityRequest) GetKillSwitchEnabled() bool {
	if x != nil {
		return x.KillSwitchEnabled
	}
	return false
}

func (x *UpdateSecurityRequest) GetDnsProtectionEnabled() bool {
	if x != nil {
		return x.DnsProtectionEnabled
	}
	return false
}

func (x *UpdateSecurityRequest) GetIpObfuscationEnabled() bool {
	if x != nil {
		return x.IpObfuscationEnabled
	}
	return false
}

func (x *UpdateSecurityRequest) GetDataEncryptionEnabled() bool {
	if x != nil {
		return x.DataEncryptionEnabled
	}
	return false
}

type SecurityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecurityResponse) Reset() {
	*x = SecurityResponse{}
	mi := &file_security_security_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecurityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecurityResponse) ProtoMessage() {}

func (x *SecurityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_security_security_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecurityResponse.ProtoReflect.Descriptor instead.
func (*SecurityResponse) Descriptor() ([]byte, []int) {
	return file_security_security_proto_rawDescGZIP(), []int{5}
}

func (x *SecurityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SecurityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_security_security_proto protoreflect.FileDescriptor

const file_security_security_proto_rawDesc = "" +
	"\n" +
	"\x17security/security.proto\x12\bsecurity\"\x17\n" +
	"\x15SecurityStatusRequest\"\x9a\x02\n" +
	"\x16SecurityStatusResponse\x12,\n" +
	"\x12kill_switch_active\x18\x01 \x01(\bR\x10killSwitchActive\x122\n" +
	"\x15dns_protection_active\x18\x02 \x01(\bR\x13dnsProtectionActive\x122\n" +
	"\x15ip_obfuscation_active\x18\x03 \x01(\bR\x13ipObfuscationActive\x124\n" +
	"\x16data_encryption_active\x18\x04 \x01(\bR\x14dataEncryptionActive\x124\n" +
	"\x16overall_security_score\x18\x05 \x01(\x05R\x14overallSecurityScore\"\x12\n" +
	"\x10LeakCheckRequest\"\x83\x01\n" +
	"\x11LeakCheckResponse\x12(\n" +
	"\x10ip_leak_detected\x18\x01 \x01(\bR\x0eipLeakDetected\x12*\n" +
	"\x11dns_leak_detected\x18\x02 \x01(\bR\x0fdnsLeakDetected\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xeb\x01\n" +
	"\x15UpdateSecurityRequest\x12.\n" +
	"\x13kill_switch_enabled\x18\x01 \x01(\bR\x11killSwitchEnabled\x124\n" +
	"\x16dns_protection_enabled\x18\x02 \x01(\bR\x14dnsProtectionEnabled\x124\n" +
	"\x16ip_obfuscation_enabled\x18\x03 \x01(\bR\x14ipObfuscationEnabled\x126\n" +
	"\x17data_encryption_enabled\x18\x04 \x01(\bR\x15dataEncryptionEnabled\"F\n" +
	"\x10SecurityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x87\x02\n" +
	"\x0fSecurityService\x12V\n" +
	"\x11GetSecurityStatus\x12\x1f.security.SecurityStatusRequest\x1a .security.SecurityStatusResponse\x12E\n" +
	"\n" +
	"CheckLeaks\x12\x1a.security.LeakCheckRequest\x1a\x1b.security.LeakCheckResponse\x12U\n" +
	"\x16UpdateSecuritySettings\x12\x1f.security.UpdateSecurityRequest\x1a\x1a.security.SecurityResponseB7Z5github.com/KFN002/B-2-Torrent/services/proto/securityb\x06proto3"

var (
	file_security_security_proto_rawDescOnce sync.Once
	file_security_security_proto_rawDescData []byte
)

func file_security_security_proto_rawDescGZIP() []byte {
	file_security_security_proto_rawDescOnce.Do(func() {
		file_security_security_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_security_security_proto_rawDesc), len(file_security_security_proto_rawDesc)))
	})
	return file_security_security_proto_rawDescData
}

var file_security_security_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_security_security_proto_goTypes = []any{
	(*SecurityStatusRequest)(nil),  // 0: security.SecurityStatusRequest
	(*SecurityStatusResponse)(nil), // 1: security.SecurityStatusResponse
	(*LeakCheckRequest)(nil),       // 2: security.LeakCheckRequest
	(*LeakCheckResponse)(nil),      // 3: security.LeakCheckResponse
	(*UpdateSecurityRequest)(nil),  // 4: security.UpdateSecurityRequest
	(*SecurityResponse)(nil),       // 5: security.SecurityResponse
}
var file_security_security_proto_depIdxs = []int32{
	0, // 0: security.SecurityService.GetSecurityStatus:input_type -> security.SecurityStatusRequest
	2, // 1: security.SecurityService.CheckLeaks:input_type -> security.LeakCheckRequest
	4, // 2: security.SecurityService.UpdateSecuritySettings:input_type -> security.UpdateSecurityRequest
	1, // 3: security.SecurityService.GetSecurityStatus:output_type -> security.SecurityStatusResponse
	3, // 4: security.SecurityService.CheckLeaks:output_type -> security.LeakCheckResponse
	5, // 5: security.SecurityService.UpdateSecuritySettings:output_type -> security.SecurityResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_security_security_proto_init() }
func file_security_security_proto_init() {
	if File_security_security_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_security_security_proto_rawDesc), len(file_security_security_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_security_security_proto_goTypes,
		DependencyIndexes: file_security_security_proto_depIdxs,
		MessageInfos:      file_security_security_proto_msgTypes,
	}.Build()
	File_security_security_proto = out.File
	file_security_security_proto_goTypes = nil
	file_security_security_proto_depIdxs = nil
}
