#!/usr/bin/env node

import { randomBytes } from "node:crypto"
import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"
import os from "node:os"

const scriptDir = dirname(fileURLToPath(import.meta.url))
const rootDir = dirname(scriptDir)
const force = process.argv.includes("--force")

const envPath = join(rootDir, ".env")
const frontendEnvPath = join(rootDir, "frontend", ".env.local")

function secret(bytes = 32) {
  return randomBytes(bytes).toString("base64url")
}

function envValue(value) {
  if (/^[A-Za-z0-9_./:@-]+$/.test(value)) {
    return value
  }
  return JSON.stringify(value)
}

if (existsSync(envPath) && !force) {
  console.error(".env already exists. Re-run with --force to replace it.")
  process.exit(1)
}

const downloadDir = join(os.homedir(), "Downloads", "B2Torrent")
const dbPassword = secret(24)
const rabbitPassword = secret(24)

const rootEnv = `# Generated by scripts/gen-env.mjs
COMPOSE_PROJECT_NAME=b2torrent

# Local bind ports
HTTP_PORT=80
FRONTEND_PORT=3000
BACKEND_PORT=8080
POSTGRES_PORT=5432
REDIS_PORT=6379
RABBITMQ_PORT=5672
RABBITMQ_MANAGEMENT_PORT=15672
TOR_SOCKS_PORT=9050

# Storage
DOWNLOAD_DIR=${envValue(downloadDir)}

# Database
POSTGRES_USER=torrentuser
POSTGRES_DB=torrentdb
DB_PASSWORD=${dbPassword}

# Messaging
RABBITMQ_USER=b2t_admin
RABBITMQ_PASS=${rabbitPassword}

# Privacy defaults
TOR_ENABLED=true
PROXY_CHAIN=tor:9050
NO_LOGS_MODE=true
OBFUSCATE_TRAFFIC=true
LOG_LEVEL=warn
CORS_ALLOWED_ORIGINS=http://localhost,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:3000

# Keep external IP/geolocation leak checks disabled unless explicitly needed.
NEXT_PUBLIC_ENABLE_EXTERNAL_LEAK_CHECKS=false
`

const frontendEnv = `# Generated by scripts/gen-env.mjs
NEXT_PUBLIC_API_URL=/api
NEXT_PUBLIC_ENABLE_EXTERNAL_LEAK_CHECKS=false
`

mkdirSync(join(rootDir, "frontend"), { recursive: true })
writeFileSync(envPath, rootEnv, { mode: 0o600 })
writeFileSync(frontendEnvPath, frontendEnv, { mode: 0o600 })

console.log("Generated .env and frontend/.env.local")
console.log(`Download directory: ${downloadDir}`)
